[workspace]
channels = ["https://prefix.dev/conda-forge","conda-forge",]
platforms = ["linux-64"]
preview = ["pixi-build"]                                  


[dependencies]
librdkit-dev = ">=2024.0.0"
fast_mces_lower_bound = { path = "." }
python = "*"
cmake = "*"
ninja = "*"
nanobind = ">=2.4.0"
# rdkit = ">=2024.0.0"
cxx-compiler = "*"
boost-cpp = "*"
eigen = "*"

[tasks]
# Configure CMake
clean = { cmd = ["bash", "-c", "[ -d ./.build ] && rm -rf ./.build || true"] }
configure = { cmd = [
    "cmake",
    "-G",
    "Ninja",
    "-S",
    ".",
    "-B",
    ".build",
    "-DCMAKE_BUILD_TYPE=Release",
    "DCMAKE_USE"
], depends-on = ["clean"]}

# Build the project (depends on configure)
build = { cmd = ["ninja", "-C", ".build"], depends-on = ["configure"] }
install = { cmd = ["cp", "-r", ".build/fast_mces_lower_bound*.so", "."], depends-on = ["build"] }
start = { cmd = "python -c 'import fast_mces_lower_bound'"}#, depends-on = ["install"] }

[package]
name = "fast_mces_lower_bound"
version = "0.1.0"
authors = ["Nir Cohen"]

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "conda-forge",
]
[package.build.configuration]
# This will run cmake, build and install the package
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] 

[package.build-dependencies]
cmake = "*"
ninja = "*"
nanobind = ">=2.4.0"
python = "*"
# rdkit = ">=2024.0.0"
librdkit-dev = ">=2024.0.0"
cxx-compiler = "*"
boost-cpp = "*"
eigen = "*"
[package.host-dependencies]
cmake = "*"
ninja = "*"
nanobind = ">=2.4.0"
python = "*"
# rdkit = ">=2024.0.0"
librdkit-dev = ">=2024.0.0"
cxx-compiler = "*"
boost-cpp = "*"
eigen = "*"

[package.run-dependencies]
# The runtime dependencies of the package
# rdkit = ">=2024.0.0"
librdkit-dev = ">=2024.0.0"
