[workspace]
channels = ["https://prefix.dev/conda-forge","conda-forge",]
platforms = ["linux-64",'win-64']
preview = ["pixi-build"]                                  


[dependencies]
fast_mces_lower_bound = { path = "."}
python = "*"
numpy = "*"
polars = "*"
[tasks]
start = { cmd = "python -c 'import fast_mces_lower_bound'"}
test = "python tests/test.py"
benchmark = "python tests/benchmark.py"

[package]
name = "fast_mces_lower_bound"
version = "1.0.0"
authors = ["Nir Cohen"]

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*"}
[package.build.config]
# The rdkit args are needed, since cmake wasn't able to find the rdkit paths by itself, and needs them to be given 
extra-args = [
  "-DCMAKE_BUILD_TYPE=Release",
  "-DRDKIT_INCLUDE_DIR=${PREFIX}/include/rdkit",
  "-DRDKIT_LIB_DIR=${PREFIX}/lib",
  # "-DFAST_MCES_PROFILE=1"
]


[package.host-dependencies]
nanobind = ">=2.4.0"
librdkit-dev = ">=2024.0.0"
boost-cpp = "*"
python = ">=3.8"
[package.build-dependencies]#these are necessery for the nanobind stuff to work
nanobind = ">=2.4.0"
librdkit-dev = ">=2024.0.0"
boost-cpp = "*"
python = ">=3.8"

[package.run-dependencies]
# The runtime dependencies of the package
# we can use any one of the 3, just need the .so files
# librdkit-dev = ">=2024.0.0" 
# rdkit = ">=2024.0.0"
librdkit = ">=2024.0.0"