[workspace]
authors = ["Nir"]
channels = ["https://prefix.dev/conda-forge"]
name = "mces_splitting"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
test = "python src/mces_splitting/test.py"
splitting_test = "python -m src.mces_splitting.dataset_splitting"

[dependencies]
fast_mces_lower_bound = { path = "packages/fast_mces_lower_bound" }
# mces_splitting = { path = "." }
python = ">=3.12.0"
pulp = ">=2.8.0,<3"
# rdkit = ">=2024.0.0"
[pypi-dependencies]
hrms_utils = {version = "==0.2.1.post1" ,index = "https://test.pypi.org/simple"}
ipykernel = "*"
polars = ">=1.32.0,<2"
# numpy = "*"
# scipy = "*"
networkx = ">=3.5,<4"
rustworkx = ">=0.17.1, <0.18"

[package]
name = "mces_splitting"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies] 
python = ">=3.12.0"
pip = "*"
hatchling = "*"
numpy = "*"
[package.run-dependencies] 
fast_mces_lower_bound = { path = "packages/fast_mces_lower_bound" }
# rdkit = ">=2024.0.0"
polars = ">=1.32.0,<2"
# numpy = "*"
scipy = "*"
networkx = ">=3.5,<4"
