[workspace]
authors = ["Nir"]
channels = [
    "https://prefix.dev/rapidsai",
    "https://prefix.dev/conda-forge",
    "https://prefix.dev/nvidia",
    "https://prefix.dev/nir-cohen"
]
name = "mces_splitting"
platforms = ["linux-64"]
preview = ["pixi-build"]
channel-priority = "disabled"
[system-requirements]
cuda = "13.0"
[package]
name = "mces_splitting"
version = "0.4.0"
authors = ["Nir"]
description = "MCES-based dataset splitting"

[tasks]
splitting_test = "python tests/splitting_test.py --skip-exact 2000"
splitting_test_exact = "python tests/splitting_test.py 2000"
splitting_test_full = "python tests/splitting_test.py"
bounds_validity_test = "python tests/bounds_test.py"
upper_bound_test = "python tests/test_mces_upper_bound_vs_exact.py"
benchmark_bounds = "python benchmarks/benchmark_bounds.py"
benchmark_cuopt = "python benchmarks/benchmark_cuopt.py"
publish-prefix = {cmd="rattler-build upload prefix --channel nir-cohen"}
publish-anaconda = {cmd="rattler-build upload anaconda --owner Nir_Cohen --channel main"}

[dependencies]
mces_splitting = { path = "." }
python = "3.12.*"
hrms_utils = ">=0.6.2"
psutil = "*"
nvidia-ml-py = "*"

[pypi-dependencies]
ipykernel = "*"


[package.build]
backend = { name = "pixi-build-python", version = ">=0.3.2" }

[package.host-dependencies]
python = "*"
pip = "*"
hatchling = "*"

[package.run-dependencies]
fast_mces_lower_bound = { path = "packages/fast_mces_lower_bound" }
rdkit = ">=2024.0.0"
polars = ">=1.32.0,<2"
numpy = ">=2.0.0,<2.3.0"
scipy = "*"
networkx = "*"
pulp = "*"
umap-learn = "*"
hdbscan = "*"
cuopt="26.06.*"
cupy = { version = ">=13.6.0", channel = "conda-forge" }
