[workspace]
authors = ["Nir <<>>"]
channels = ["conda-forge"]
name = "test_rdkit"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = {cmd = "cmake --build ./.build",depends-on = ['configure']}
configure = {cmd = "cmake -S . -B ./.build",depends-on = ['clean']}
clean = "rm -rf ./.build"
[dependencies]
python = "*"
cmake = "*"
librdkit-dev = "*"
boost-cpp = "*"
eigen = "*"
